export const Events = {
  getConfiguration: 'getConfiguration',
  editConfiguration: 'editConfiguration',
  editConfigurationSuccess: 'editConfigurationSuccess',

  getItems: 'getItems',
  getItemsSuccess: 'getItemsSuccess',
  getItemsError: 'getItemsError',
  addItem: 'addItem',
  addItemSuccess: 'addItemSuccess',
  addItemError: 'addItemError',
  editItem: 'editItem',
  editItemSuccess: 'editItemSuccess',
  editItemError: 'editItemError',
  removeItem: 'removeItem',
  removeItemSuccess: 'removeItemSuccess',
  removeItemError: 'removeItemError',

  getOrders: 'getOrders',
  getOrdersSuccess: 'getOrdersSuccess',
  getOrdersError: 'getOrdersError',
  addOrder: 'addOrder',
  addOrderSuccess: 'addOrderSuccess',
  addOrderError: 'addOrderError',
  editOrder: 'editOrder',
  editOrderSuccess: 'editOrderSuccess',
  editOrderError: 'editOrderError',
  removeOrder: 'removeOrder',
  removeOrderSuccess: 'removeOrderSuccess',
  removeOrderError: 'removeOrderError',
  proceedOrder: 'proceedOrder',
  proceedOrderError: 'proceedOrderError',
  proceedOrderSuccess: 'proceedOrderSuccess',

  showDevConsole: 'showDevConsole',

  printReceiptToPDF: 'printReceiptToPDF',
  printReceiptToDocx: 'printReceiptToDocx',
  printReceiptToDocxSuccess: 'printReceiptToDocxSuccess',
  printReportToDocx: 'printReportToDocx',
  printReportToDocxSuccess: 'printReportToDocxSuccess',

  setPrintReceiptDocxTemplate: 'setPrintReceiptDocxTemplate',
  setPrintReceiptDocxTemplateSuccess: 'setPrintReceiptDocxTemplateSuccess',
  getPrintReceiptDocxTemplate: 'getPrintReceiptDocxTemplate',

  setPrintReportDocxTemplate: 'setPrintReportDocxTemplate',
  setPrintReportDocxTemplateSuccess: 'setPrintReportDocxTemplateSuccess',
  getPrintReportDocxTemplate: 'getPrintReportDocxTemplate',

  error: 'error',
};
